name: Run Tests

on:
  push:
    branches:
      - alpha

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Debug Workflow Run
        run: |
          echo "Workflow: ${{ github.workflow }}"
          echo "Workflow Run Job: ${{ github.job }}"
          echo "Workflow Run Ref: ${{ github.ref }}"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

  e2e-tests:
    name: E2E Tests
    needs: unit-tests
    if: ${{ needs.unit-tests.result == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Debug Workflow Run
        run: |
          echo "Workflow: ${{ github.workflow }}"
          echo "Workflow Run Job: ${{ github.job }}"
          echo "Workflow Run Ref: ${{ github.ref }}"

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests
        run: npm run test:e2e

  notify-release:
    name: Notify Release
    needs: e2e-tests
    if: ${{ needs.e2e-tests.result == 'success' }}
    permissions:
      contents: write
      actions: write

    runs-on: ubuntu-latest

    steps:
      - name: Trigger Release Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Release
